#!/usr/bin/env python3
"""Offline synthetic tests; never attach to WeCom or discover real account data."""

from __future__ import annotations

import argparse
import builtins
import contextlib
import hashlib
import io
import json
import os
from pathlib import Path
import queue
import runpy
import shutil
import subprocess
import tempfile
import unittest
from unittest import mock

from Crypto.Cipher import ARC4

import scan_dbkey_manager_frida_macos as scan
import wecom_common
from wecom_crypto import PAGE_SIZE, SQLITE_HEADER, encrypt_page_for_test


# Generated by compiling the original GenerateKeyAES128Cipher, PadPassword,
# RC4 and md5 C routines at SQLite3MultipleCiphers commit
# 7a7f16a5270e0157db43c8c3cfcf6088e11f72b1 (no account-derived input).
C_REFERENCE_VECTORS = (
    (b"", "1ed0b3d11eb935d323e975766e80cc70"),
    (bytes(range(16)), "6f27390c4f18b65d4c1dca626d7ad304"),
    (bytes(16), "c473ef19fb62836c664b7d42f5200993"),
    (bytes(range(32)), "5e135cc6753523e3f7fdf58f842342a8"),
    (bytes(range(48)), "5e135cc6753523e3f7fdf58f842342a8"),
    (bytes(range(128, 144)), "80176cb995967b2c4e9bfb0aee48f867"),
    (b"hello\x00world", "94d8fc48255d79a09931b71569530d79"),
)


def reference_kdf(password):
    """Equivalent C sequence using the independent PyCryptodome ARC4 primitive."""
    padding = bytes.fromhex(
        "28bf4e5e4e758a4164004e56fffa01082e2e00b6d0683e802f0ca9fe6453697a"
    )
    user = (password + padding)[:32]
    digest = hashlib.md5(padding).digest()
    for _ in range(50):
        digest = hashlib.md5(digest).digest()
    owner = user
    for round_number in range(20):
        owner = ARC4.new(bytes(value ^ round_number for value in digest)).encrypt(owner)
    digest = hashlib.md5(user + owner).digest()
    for _ in range(50):
        digest = hashlib.md5(digest).digest()
    return digest


def synthetic_page(master):
    page = bytearray(PAGE_SIZE)
    page[:16] = SQLITE_HEADER
    page[16:18] = PAGE_SIZE.to_bytes(2, "big")
    page[21:24] = b"\x40\x20\x20"
    page[100] = 0x0D
    return encrypt_page_for_test(master, bytes(page), 1)


class DerivationTests(unittest.TestCase):
    def test_official_c_fixed_vectors_and_independent_arc4(self):
        for password, expected in C_REFERENCE_VECTORS:
            with self.subTest(password=password.hex()):
                self.assertEqual(reference_kdf(password).hex(), expected)
                self.assertEqual(scan.derive_wxaes128_master(password).hex(), expected)

    def test_rc4_standard_vector(self):
        self.assertEqual(scan.rc4(b"Key", b"Plaintext").hex(), "bbf316e8d940af0ad3")
        with self.assertRaises(ValueError):
            scan.rc4(b"", b"anything")

    def test_password_and_raw_are_distinguished_by_real_page_validation(self):
        password = bytes(range(16))
        for mode, master in (("wxaes128-pdf-kdf", reference_kdf(password)), ("raw", password)):
            with self.subTest(mode=mode), tempfile.TemporaryDirectory() as temp:
                dataset = Path(temp)
                for name in scan.CORE_DATABASES:
                    (dataset / name).write_bytes(synthetic_page(master))
                validated = scan.validate_password(password, dataset, wecom_common.validate_candidate)
                self.assertIsNotNone(validated)
                self.assertEqual(validated[:2], (mode, master))
                self.assertEqual(set(validated[2]), scan.CORE_DATABASES)

    def test_password_derivation_is_checked_before_raw(self):
        validate = mock.Mock(return_value=list(scan.CORE_DATABASES))
        candidate = bytes(range(16))
        self.assertEqual(scan.validate_password(candidate, Path("synthetic"), validate)[0], "wxaes128-pdf-kdf")
        validate.assert_called_once_with(reference_kdf(candidate), Path("synthetic"))

    def test_all_three_root_core_databases_are_required(self):
        for accepted in ([], ["message.db"], ["message.db", "session.db"],
                         ["nested/message.db", "session.db", "user.db"]):
            with self.subTest(accepted=accepted):
                self.assertIsNone(scan.validate_password(bytes(16), Path("synthetic"), lambda *_: accepted))

    def test_corrupted_core_page_rejects_the_candidate(self):
        candidate = bytes(range(16))
        with tempfile.TemporaryDirectory() as temp:
            dataset = Path(temp)
            for name in scan.CORE_DATABASES:
                key = bytes(16) if name == "user.db" else reference_kdf(candidate)
                (dataset / name).write_bytes(synthetic_page(key))
            self.assertIsNone(scan.validate_password(candidate, dataset, wecom_common.validate_candidate))

    def test_non_16_byte_candidates_never_reach_database_validation(self):
        validate = mock.Mock()
        for candidate in (b"", bytes(15), bytes(17), bytes(64)):
            self.assertIsNone(scan.validate_password(candidate, Path("synthetic"), validate))
        validate.assert_not_called()


class FakeCancelled(Exception):
    pass


class FakeCancellable:
    def __init__(self):
        self.cancelled = False

    def __enter__(self):
        return self

    def __exit__(self, *_):
        return False

    def cancel(self):
        self.cancelled = True


class FakeFrida:
    Cancellable = FakeCancellable
    OperationCancelledError = FakeCancelled

    def __init__(self, messages=(), fail=None):
        self.messages = messages
        self.fail = fail
        self.calls = []
        self.callback = None

    def step(self, name):
        self.calls.append(name)
        if self.fail == name:
            raise RuntimeError("synthetic private path /private/test and secret must stay hidden")

    def get_local_device(self):
        self.step("get_local_device")
        return self

    def attach(self, pid):
        self.step("attach")
        return self

    def create_script(self, source):
        self.step("create_script")
        return self

    def on(self, event, callback):
        self.step("on")
        self.callback = callback

    def load(self):
        self.step("load")
        for payload in self.messages:
            self.callback({"type": "send", "payload": payload}, None)

    def unload(self):
        self.step("unload")

    def detach(self):
        self.step("detach")


CANDIDATE = {"type": "candidate", "key": bytes(range(16)).hex()}
DONE = {"type": "done", "ranges": 1, "matches": 1, "candidates": 1}


class LifecycleTests(unittest.TestCase):
    def setUp(self):
        self.args = argparse.Namespace(confirm_attach=True, pid=123, data_dir="synthetic-dataset")
        self.choose = mock.Mock(return_value=Path("synthetic-dataset"))
        self.save = mock.Mock()
        self.validate = mock.Mock(return_value=list(scan.CORE_DATABASES))
        self.output = io.StringIO()
        self.stack = contextlib.ExitStack()
        self.stack.enter_context(contextlib.redirect_stdout(self.output))
        self.stack.enter_context(contextlib.redirect_stderr(self.output))
        self.preflight = self.stack.enter_context(mock.patch.object(scan, "check_installed_version"))
        self.addCleanup(self.stack.close)

    def run_scan(self, frida):
        return scan.scan_and_save(self.args, self.choose, self.save, self.validate, frida=frida)

    def test_success_cleans_up_before_saving_only_derived_key(self):
        frida = FakeFrida((CANDIDATE, DONE))
        self.save.side_effect = lambda *_: self.assertEqual(frida.calls[-2:], ["unload", "detach"])
        self.assertEqual(self.run_scan(frida), 0)
        self.save.assert_called_once_with(reference_kdf(bytes(range(16))), Path("synthetic-dataset"), list(scan.CORE_DATABASES))
        self.assertNotIn(CANDIDATE["key"], self.output.getvalue())
        self.assertNotIn("synthetic-dataset", self.output.getvalue())

    def test_failed_or_partial_validation_does_not_save(self):
        for accepted in ([], ["message.db", "session.db"]):
            self.validate.return_value = accepted
            self.assertEqual(self.run_scan(FakeFrida((CANDIDATE, DONE))), 2)
        self.save.assert_not_called()

    def test_malformed_candidate_does_not_save(self):
        self.assertEqual(self.run_scan(FakeFrida(({"type": "candidate", "key": "not-hex"}, DONE))), 2)
        self.validate.assert_not_called()
        self.save.assert_not_called()

    def test_failures_at_each_acquisition_stage_clean_owned_resources(self):
        for stage, expected_cleanup in (("get_local_device", []), ("attach", []),
                                        ("create_script", ["detach"]), ("on", ["unload", "detach"]),
                                        ("load", ["unload", "detach"])):
            with self.subTest(stage=stage):
                frida = FakeFrida((CANDIDATE, DONE), fail=stage)
                with self.assertRaises(RuntimeError):
                    self.run_scan(frida)
                self.assertEqual([name for name in frida.calls if name in ("unload", "detach")], expected_cleanup)
        self.save.assert_not_called()

    def test_cleanup_failure_prevents_saving_and_detach_still_runs(self):
        for stage in ("unload", "detach"):
            with self.subTest(stage=stage):
                frida = FakeFrida((CANDIDATE, DONE), fail=stage)
                self.assertEqual(self.run_scan(frida), 1)
                self.assertEqual(frida.calls[-2:], ["unload", "detach"])
        self.save.assert_not_called()
        self.assertNotIn("private path", self.output.getvalue())

    def test_validation_exception_cleans_up_and_does_not_save(self):
        self.validate.side_effect = OSError("private")
        frida = FakeFrida((CANDIDATE, DONE))
        with self.assertRaises(OSError):
            self.run_scan(frida)
        self.assertEqual(frida.calls[-2:], ["unload", "detach"])
        self.save.assert_not_called()

    def test_agent_error_is_controlled_and_cleans_up(self):
        frida = FakeFrida(({"type": "error", "description": "private data"},))
        with self.assertRaisesRegex(RuntimeError, "^instrumentation failed$"):
            self.run_scan(frida)
        self.assertEqual(frida.calls[-2:], ["unload", "detach"])
        self.save.assert_not_called()

    def test_event_timeout_cleans_up_without_sleeping(self):
        frida = FakeFrida()
        with mock.patch.object(scan.queue.Queue, "get", side_effect=queue.Empty):
            with self.assertRaises(scan.StageTimeout):
                self.run_scan(frida)
        self.assertEqual(frida.calls[-2:], ["unload", "detach"])
        self.save.assert_not_called()

    def test_late_timeout_retains_resource_for_cleanup(self):
        for timeout_stage, cleanup in (("attach", ["detach"]), ("create_script", ["unload", "detach"])):
            frida = FakeFrida()
            def stage(_frida, name, seconds, action):
                result = action()
                if name == timeout_stage:
                    raise scan.StageTimeout(name)
                return result
            with self.subTest(stage=timeout_stage), mock.patch.object(scan, "frida_stage", side_effect=stage):
                with self.assertRaises(scan.StageTimeout):
                    self.run_scan(frida)
                self.assertEqual(frida.calls[-len(cleanup):], cleanup)
        self.save.assert_not_called()

    def test_explicit_directory_failure_cannot_fall_back(self):
        self.choose.side_effect = SystemExit("private account path")
        frida = FakeFrida()
        with self.assertRaisesRegex(RuntimeError, "^cannot select the explicit dataset$"):
            self.run_scan(frida)
        self.assertEqual(frida.calls, [])
        self.save.assert_not_called()

    def test_direct_call_consent_and_empty_directory_gate_precedes_system_access(self):
        for changes in ({"confirm_attach": False}, {"data_dir": ""}, {"data_dir": "   "}, {"pid": 0}):
            args = vars(self.args) | changes
            frida = FakeFrida()
            with self.subTest(changes=changes), self.assertRaises(RuntimeError):
                scan.scan_and_save(argparse.Namespace(**args), self.choose, self.save, self.validate, frida=frida)
            self.assertEqual(frida.calls, [])
        self.preflight.assert_not_called()
        self.choose.assert_not_called()

    def test_save_uses_restrictive_umask_and_restores_it_on_failure(self):
        seen = []
        def save(*_):
            current = os.umask(0o077)
            seen.append(current)
            os.umask(current)
            raise OSError("synthetic save failure")
        self.save.side_effect = save
        previous = os.umask(0o022)
        try:
            with self.assertRaises(OSError):
                self.run_scan(FakeFrida((CANDIDATE, DONE)))
            restored = os.umask(0o022)
        finally:
            os.umask(previous)
        self.assertEqual(seen, [0o077])
        self.assertEqual(restored, 0o022)

    def test_actual_helper_saves_private_file_under_synthetic_temp_root(self):
        with tempfile.TemporaryDirectory() as temp, mock.patch.object(wecom_common, "vault_root", return_value=Path(temp)):
            self.save = wecom_common.save_validated_key
            self.assertEqual(self.run_scan(FakeFrida((CANDIDATE, DONE))), 0)
            paths = list((Path(temp) / "private").glob("keys-*.json"))
            self.assertEqual(len(paths), 1)
            self.assertEqual(paths[0].stat().st_mode & 0o777, 0o600)
            self.assertEqual(paths[0].parent.stat().st_mode & 0o777, 0o700)
            saved = json.loads(paths[0].read_text())
            self.assertEqual(saved["global_key"], reference_kdf(bytes(range(16))).hex())


class ConsentAndErrorsTests(unittest.TestCase):
    def test_cli_rejects_missing_consent_and_empty_directory_before_helper_import(self):
        original_import = builtins.__import__
        def guarded_import(name, *args, **kwargs):
            if name in ("frida", "wecom_common"):
                self.fail("system helper imported before consent validation")
            return original_import(name, *args, **kwargs)
        cases = (["--pid", "123", "--data-dir", "synthetic"],
                 ["--confirm-attach", "--pid", "123", "--data-dir", ""],
                 ["--confirm-attach", "--pid", "123", "--data-dir", "   "])
        with mock.patch("builtins.__import__", side_effect=guarded_import), contextlib.redirect_stderr(io.StringIO()):
            for argv in cases:
                with self.subTest(argv=argv), self.assertRaises(SystemExit) as error:
                    scan.main(argv)
                self.assertEqual(error.exception.code, 2)

    def test_import_neither_imports_live_helpers_nor_checks_installation(self):
        original_import = builtins.__import__
        def guarded_import(name, *args, **kwargs):
            if name in ("frida", "wecom_common"):
                self.fail("scanner import loaded a live helper")
            return original_import(name, *args, **kwargs)
        with mock.patch("builtins.__import__", side_effect=guarded_import), \
             mock.patch.object(Path, "read_bytes", side_effect=AssertionError("read data during import")):
            runpy.run_path(scan.__file__, run_name="offline_import_test")

    def test_main_error_does_not_disclose_filesystem_or_candidate_values(self):
        for error in (OSError("/private/example/secret.db"), SystemExit("private candidate")):
            output = io.StringIO()
            with mock.patch.object(scan, "scan_and_save", side_effect=error), contextlib.redirect_stderr(output):
                self.assertEqual(scan.main(["--confirm-attach", "--pid", "123", "--data-dir", "synthetic"]), 1)
            self.assertNotIn("private", output.getvalue())
            self.assertNotIn("candidate", output.getvalue())

    def test_plist_preflight_accepts_only_exact_version_and_build(self):
        for info, accepted in (({"CFBundleShortVersionString": "5.0.11", "CFBundleVersion": "70742"}, True),
                               ({"CFBundleShortVersionString": "5.0.9", "CFBundleVersion": "70699"}, False),
                               ({"CFBundleShortVersionString": "5.0.11", "CFBundleVersion": "70743"}, False)):
            with self.subTest(info=info), mock.patch.object(Path, "read_bytes", return_value=scan.plistlib.dumps(info)):
                if accepted:
                    scan.check_installed_version()
                else:
                    with self.assertRaisesRegex(RuntimeError, "unsupported WeCom version"):
                        scan.check_installed_version()

    def test_stage_timeout_cancels_and_reports_only_stage(self):
        frida = FakeFrida()
        class ImmediateTimer:
            def __init__(self, seconds, callback):
                self.callback = callback
            def start(self):
                self.callback()
            def cancel(self):
                pass
        with mock.patch.object(scan.threading, "Timer", ImmediateTimer), contextlib.redirect_stdout(io.StringIO()):
            with self.assertRaisesRegex(scan.StageTimeout, "^attach$"):
                scan.frida_stage(frida, "attach", 1, lambda: (_ for _ in ()).throw(FakeCancelled("private")))


# A sparse, synthetic address space implements only APIs the injected agent uses.
# Running AGENT with Node exercises its actual architecture/UUID gates and libc++
# string handling without Frida, a native process, or a real account directory.
NODE_HARNESS = r"""
const fs = require('fs');
const vm = require('vm');
const {agent, config} = JSON.parse(fs.readFileSync(0, 'utf8'));
const memory = new Map();
const base = 0x100000000n, heap = 0x200000000n, external = heap + 0x200n;
const vtable = base + 0x0cd5fb50n;
const messages = [];
let scans = 0;
function write(address, bytes) { for (const byte of bytes) memory.set(address++, byte); }
function u32(address, value) { const b = Buffer.alloc(4); b.writeUInt32LE(value); write(address, b); }
function u64(address, value) { const b = Buffer.alloc(8); b.writeBigUInt64LE(BigInt(value)); write(address, b); }
class Pointer {
  constructor(value) { this.value = BigInt(value); }
  add(value) { return new Pointer(this.value + BigInt(value)); }
  compare(other) { return this.value < other.value ? -1 : this.value > other.value ? 1 : 0; }
  isNull() { return this.value === 0n; }
  toString() { return '0x' + this.value.toString(16); }
  readByteArray(size) {
    const result = new Uint8Array(size);
    for (let i = 0; i < size; i++) {
      const value = memory.get(this.value + BigInt(i));
      if (value === undefined) throw new Error('unmapped synthetic read');
      result[i] = value;
    }
    return result.buffer;
  }
  readU8() { return new Uint8Array(this.readByteArray(1))[0]; }
  readU32() { return Buffer.from(this.readByteArray(4)).readUInt32LE(); }
  readU64() { return Buffer.from(this.readByteArray(8)).readBigUInt64LE(); }
  readPointer() { return new Pointer(this.readU64()); }
}
write(base, Buffer.alloc(64));
u32(base, 0xfeedfacf); u32(base + 4n, 0x0100000c);
u32(base + 16n, 1); u32(base + 20n, 24);
u32(base + 32n, 0x1b); u32(base + 36n, 24);
write(base + 40n, Buffer.from(config.uuid || 'BBC8DDE9AC043DF1BF5AD6887B956966', 'hex'));
write(heap, Buffer.alloc(256));
u32(heap + 0x60n, 1);
const candidate = Buffer.from(Array.from({length: 16}, (_, i) => i));
if (config.longString) {
  u64(heap + 0x68n, external); u64(heap + 0x70n, 16);
  write(heap + 0x7fn, [0x80]); write(external, candidate);
} else {
  write(heap + 0x68n, candidate); write(heap + 0x7fn, [16]);
}
const regions = [{base: new Pointer(base), size: 64, protection: 'r--'},
                 {base: new Pointer(heap), size: 0x300, protection: 'rw-'}];
if (config.vtableReadable !== false) regions.push({base: new Pointer(vtable), size: 16, protection: 'r--'});
const context = {
  Process: {
    arch: config.arch || 'arm64', pointerSize: config.pointerSize || 8,
    enumerateModules: () => config.missingModule ? [] : [{base: new Pointer(base), path: '/synthetic/Contents/MacOS/企业微信'}],
    findRangeByAddress: pointer => regions.find(r => pointer.compare(r.base) >= 0 && pointer.compare(r.base.add(r.size)) < 0) || null,
    enumerateRanges: () => [regions[1]],
  },
  Memory: {scanSync: (_base, _size, pattern) => {
    scans++;
    const expected = Buffer.alloc(8); expected.writeBigUInt64LE(vtable);
    if (pattern !== expected.toString('hex').match(/../g).join(' ')) throw new Error('incorrect pointer pattern');
    return [{address: new Pointer(heap)}, {address: new Pointer(heap)}];
  }},
  send: payload => messages.push(payload),
};
vm.runInNewContext(agent, context, {timeout: 2000});
process.stdout.write(JSON.stringify({scans, messages}));
"""


@unittest.skipUnless(shutil.which("node"), "Node.js is required for the offline injected-JavaScript simulator")
class AgentJavaScriptTests(unittest.TestCase):
    def run_agent(self, config):
        result = subprocess.run([shutil.which("node"), "-e", NODE_HARNESS],
                                input=json.dumps({"agent": scan.AGENT, "config": config}),
                                text=True, capture_output=True, check=True, timeout=5)
        return json.loads(result.stdout)

    def test_runtime_mismatch_never_reaches_memory_scan(self):
        for config in ({"arch": "x64"}, {"pointerSize": 4}, {"uuid": "00" * 16},
                       {"missingModule": True}, {"vtableReadable": False}):
            with self.subTest(config=config):
                result = self.run_agent(config)
                self.assertEqual(result["scans"], 0)
                self.assertEqual([message["type"] for message in result["messages"]], ["error"])

    def test_supported_runtime_reads_short_and_long_libcpp_strings(self):
        for long_string in (False, True):
            with self.subTest(long_string=long_string):
                result = self.run_agent({"longString": long_string})
                self.assertEqual(result["scans"], 1)
                self.assertEqual(result["messages"], [
                    {"type": "candidate", "key": bytes(range(16)).hex(), "version": 1},
                    {"type": "done", "ranges": 1, "matches": 2, "candidates": 1},
                ])


if __name__ == "__main__":
    unittest.main(verbosity=2)
